name: "Sanity"
on:
  pull_request
jobs:
  runTests:
    name: Cypress run
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install packages
        run: npm i
        timeout-minutes: 5
      - name: Build the project
        run: npm run build &
      - name: Start local server
        run: npm run start-server &
      - name: Run Cypress tests
        run: npx cypress run
  runPlaywrightTests:
    name: Playwright run
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install packages
        run: npm i
        timeout-minutes: 5
      - name: Build the project
        run: npm run build &
      - name: Start local server
        run: npm run start-server &
      - name: Run Cypress tests
        run: npx playwright test
